version: '3'

services:
  deployment:
    build:
      context: .
      dockerfile: Dockerfile
    image: "llm-gen-ai-project"
    ports:
      - "5000:5000"
    container_name: "llm-gen-ai-project_cn"
    restart: unless-stopped
    command: bash -c "while true; do sleep 1; done"
